# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

# Enable AndroidX support (required for Jetpack Compose & modern Android libraries)
android.useAndroidX=true
# Jetifier is not needed as all dependencies are already modern AndroidX
android.enableJetifier=false

# Kotlin code style
kotlin.code.style=official
